POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Sumit",
    "details" : "Um evento para quem é apaixonado por programação",
    "maximunAttendes" : 100
}

###

POST http://localhost:3333/events/6059988b-d2f0-4a0f-9c0c-bfd8c9e80df8/attendees
Content-Type: application/json

{
    "name": "Jhon Rodrigues",
    "email": "jhon.rodigues@gmail.com"
}

###
GET http://localhost:3333/events/a6abed96-aa15-4423-8418-3c30aea470b9

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in

###
GET http://localhost:3333/events/a6abed96-aa15-4423-8418-3c30aea470b9/attendees?query=jhon